name: Maven Package upon a push

on:
  release:
    types: [published]
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
    inputs:
      message:
        description: 'Message for manually triggering'
        required: false
        default: 'Triggered for Updates'
        type: string
  push:
    branches:
      - tf_myanmar

jobs:
  build-maven-pre-registration:
    uses: ./github/workflows/maven-build.yaml@tf_myanmar
    with:
      SERVICE_LOCATION: ./pre-registration
      BUILD_ARTIFACT: pre-registration
    secrets:
      OSSRH_USER: ${{ secrets.OSSRH_USER }}
      OSSRH_SECRET: ${{ secrets.OSSRH_SECRET }}
      OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
      GPG_SECRET: ${{ secrets.GPG_SECRET }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  build-dockers:
    needs: build-maven-pre-registration
    strategy:
      matrix:
        include:
          - SERVICE_LOCATION: 'pre-registration/pre-registration-application-service'
            SERVICE_NAME: 'pre-registration-application-service'
            BUILD_ARTIFACT: 'pre-registration'
          - SERVICE_LOCATION: 'pre-registration/pre-registration-batchjob'
            SERVICE_NAME: 'pre-registration-batchjob'
            BUILD_ARTIFACT: 'pre-registration'
          - SERVICE_LOCATION: 'pre-registration/pre-registration-datasync-service'
            SERVICE_NAME: 'pre-registration-datasync-service'
            BUILD_ARTIFACT: 'pre-registration'
          - SERVICE_LOCATION: 'pre-registration/pre-registration-captcha-service'
            SERVICE_NAME: 'pre-registration-captcha-service'
            BUILD_ARTIFACT: 'pre-registration'
      fail-fast: false
    name: ${{ matrix.SERVICE_NAME }}
    uses: mosip/kattu/.github/workflows/docker-build.yml@master
    with:
      SERVICE_LOCATION: ${{ matrix.SERVICE_LOCATION }}
      SERVICE_NAME: ${{ matrix.SERVICE_NAME }}
      BUILD_ARTIFACT: ${{ matrix.BUILD_ARTIFACT }}
    secrets:
      DEV_NAMESPACE_DOCKER_HUB: ${{ secrets.DEV_NAMESPACE_DOCKER_HUB }}
      ACTOR_DOCKER_HUB: ${{ secrets.ACTOR_DOCKER_HUB }}
      RELEASE_DOCKER_HUB: ${{ secrets.RELEASE_DOCKER_HUB }}


 
